from django.urls import path

from .views import (
	AuthorDashboardAPIView,
    AuthorBookManageAPIView,
    AuthorOnboardingAPIView,
    AuthorStatusAPIView,
    BookChaptersAPIView,
    BookDetailAPIView,
    BookListCreateAPIView,
    BookReviewAPIView,
    FreeTextTTSAPIView,
    GoogleOAuthAPIView,
    LogoutAPIView,
    PurchaseBookAPIView,
    RequestOtpAPIView,
    StoryTTSAPIView,
    StoryListAPIView,
    UserAudioProgressAPIView,
    UserNotificationPreferencesAPIView,
    UserProfileStatsAPIView,
    UserBookProgressAPIView,
    UserPurchasesAPIView,
    UserReadingHistoryAPIView,
    UserProfileAPIView,
    UserSavedStoriesAPIView,
    VerifyOtpAPIView,
)

urlpatterns = [
    path('auth/request-otp', RequestOtpAPIView.as_view(), name='auth-request-otp'),
    path('auth/verify-otp', VerifyOtpAPIView.as_view(), name='auth-verify-otp'),
    path('auth/logout', LogoutAPIView.as_view(), name='auth-logout'),
    path('me/profile/', UserProfileAPIView.as_view(), name='me-profile'),
    path('me/notifications/preferences/', UserNotificationPreferencesAPIView.as_view(), name='me-notifications-preferences'),
    path('me/profile/stats/', UserProfileStatsAPIView.as_view(), name='me-profile-stats'),
    path('me/purchases/', UserPurchasesAPIView.as_view(), name='me-purchases'),
    path('me/history/', UserReadingHistoryAPIView.as_view(), name='me-history'),
    path('me/progress/reading/', UserBookProgressAPIView.as_view(), name='me-progress-reading'),
    path('me/progress/audio/', UserAudioProgressAPIView.as_view(), name='me-progress-audio'),
    path('me/saved-stories/', UserSavedStoriesAPIView.as_view(), name='me-saved-stories'),
    path('auth/google/', GoogleOAuthAPIView.as_view(), name='auth-google'),
    path('stories/', StoryListAPIView.as_view(), name='stories-list'),
    path('authors/onboard/', AuthorOnboardingAPIView.as_view(), name='authors-onboard'),
    path('authors/status/', AuthorStatusAPIView.as_view(), name='authors-status'),
    path('authors/dashboard/', AuthorDashboardAPIView.as_view(), name='authors-dashboard'),
    path('books/', BookListCreateAPIView.as_view(), name='books-list-create'),
    path('books/<int:pk>/', BookDetailAPIView.as_view(), name='books-detail'),
    path('books/<int:pk>/manage/', AuthorBookManageAPIView.as_view(), name='books-manage'),
    path('books/<int:pk>/chapters/', BookChaptersAPIView.as_view(), name='books-chapters'),
    path('purchase/<int:book_id>/', PurchaseBookAPIView.as_view(), name='books-purchase'),
    path('books/<int:pk>/review/', BookReviewAPIView.as_view(), name='books-review'),
    path('tts/story/<int:story_id>/', StoryTTSAPIView.as_view(), name='tts-story'),
    path('tts/generate/', FreeTextTTSAPIView.as_view(), name='tts-generate'),
]
