# Generated by Django 5.2.12 on 2026-03-27 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0009_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='has_audio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='Kiswahili', max_length=32),
        ),
        migrations.AddField(
            model_name='book',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='language',
            field=models.CharField(default='Kiswahili', max_length=32),
        ),
    ]
